name: Update Facts

on:
  schedule:
    - cron: '5,20,35,50 * * * *'   # 5 min depois do ingest, também a cada 15
  workflow_dispatch: {}

jobs:
  update:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Install deps
        run: npm ci

      - name: Run updater
        env:
          DATABASE_URL: ${{ secrets.DATABASE_URL }}
        run: node scripts/run-update.js
